# Generated by Django 2.2.9 on 2020-01-24 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=50)),
                ('class_instructor', models.CharField(max_length=20)),
                ('class_description', models.TextField(max_length=512)),
                ('class_created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('class_invite_code', models.CharField(default='111111', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='LectureInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=50)),
                ('lecture_type', models.IntegerField(default=0)),
                ('lecture_rsrc_path', models.CharField(max_length=256)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.ClassInformation')),
            ],
        ),
        migrations.CreateModel(
            name='QuizBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_box_title', models.CharField(max_length=30)),
                ('quiz_is_open', models.BooleanField(default=False)),
                ('lecture_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.LectureInformation')),
            ],
        ),
        migrations.CreateModel(
            name='QuizScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecture_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.LectureInformation')),
                ('quiz_box_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.QuizBox')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_prob', models.TextField(max_length=512)),
                ('quiz_type', models.IntegerField(default=0)),
                ('quiz_item_num', models.IntegerField(default=5)),
                ('quiz_score', models.IntegerField(default=1)),
                ('quiz_solve_count', models.IntegerField(default=0)),
                ('quiz_correct_count', models.IntegerField(default=0)),
                ('quiz_box_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.QuizBox')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_content', models.TextField(max_length=200)),
                ('like_count', models.IntegerField(default=0)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.LectureInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=20)),
                ('answer_choice_count', models.IntegerField(default=0)),
                ('answer_is_correct', models.BooleanField(default=False)),
                ('quiz_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Quiz')),
            ],
        ),
    ]
