# Generated by Django 2.2.9 on 2020-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='class_instructor_id',
            field=models.CharField(default='root', max_length=50),
        ),
    ]
