# Generated by Django 2.2.9 on 2020-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_classinformation_class_instructor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureinformation',
            name='lecture_rsrc_path',
        ),
        migrations.AddField(
            model_name='classinformation',
            name='class_thumbnail_path',
            field=models.FilePathField(default='/static/'),
        ),
        migrations.AddField(
            model_name='lectureinformation',
            name='lecture_pdf_path',
            field=models.FilePathField(default='/static/pdfs/'),
        ),
    ]
