# Generated by Django 2.2.9 on 2020-01-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20200127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='class_thumbnail_path',
            field=models.CharField(default='/static/storage/', max_length=100),
        ),
        migrations.AlterField(
            model_name='lectureinformation',
            name='lecture_pdf_path',
            field=models.CharField(default='/static/storage/pdf/', max_length=100),
        ),
    ]
