# Generated by Django 2.2.9 on 2020-01-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20200127_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinformation',
            name='lecture_note',
            field=models.TextField(default=''),
        ),
    ]
