# Generated by Django 2.2.9 on 2020-02-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_lectureinformation_lecture_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmessage',
            old_name='class_info',
            new_name='lecture_info',
        ),
        migrations.AddField(
            model_name='questionmessage',
            name='user_id',
            field=models.CharField(default='root', max_length=30),
        ),
    ]
