# Generated by Django 2.2.9 on 2020-03-23 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20200201_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinformation',
            name='lecture_description',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lectureinformation',
            name='lecture_ppt_times',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='BonusPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecture_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.LectureInformation')),
            ],
        ),
    ]
